language: python

python:
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt

env:
  global:
  - PYPI_USER_NAME: "chaostoolkit"
  - secure: "X2QBezwdu8xC+mk+WP7WgBZj40XkTL9xQ4O+t9Zu6EE+P8AX/jrGzyLLe8YcuINkAaJv4ioaIh3JqsJnVEm/yaBhMEurn8MVPwZNe8ViVsDZm9DpOeQR/26mgmavB1axBkmy0kRNF7spiTdTiKqi7ssbp7aOWh2MVc0MS8bs0JOFs2hLADCEXRh7p6kXVozQlDAsPuSy2NcnBb3FQWjYtP0A0XrUwRzet6SVqFybPIP7aJY4R1bcgw5SY9DJ3OxorelQyQnLoYZPMprNynX5AtzuKFc1JMIafOwG3M4GI5MijTm1umqEIWpHULeh96UnnVAo4OZkLCar1s2hTesGZv3i/4zjsMJQ5cQUOPfz/DT0YkWnGcW9vvu8f8wS4MqQATwSDkbyZs1eTvvXw6fUodi+O/Noi6sMfpVPr1I/26oXyMLpnY38Eakgmuax5iuO6HmHRHdsII5YUNdu9jw5pbjm+Zt2T/RZKYf0p8RFORDxqhoVQmKmg6hNiPxAkQRCHhOobhz2uOQZhyuq06vkisgzFTqzjCyArpoY8KfWN5GMtUlmuDNbbk3gVQhW6BhXmFMl1OXzzz/tmuiVgrKp+hRMCJVZflBfCz1sVh5HLDZeDA6fWTPRodO/vk43N1JUj2QZkyZUE5Ol6pB5vuDX/Wxyi38sSVO5r5ppuAeVIsM="

script: 
  - bash ci.bash
