language: python

python:
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt

env:
  global:
  - PYPI_USER_NAME: "chaostoolkit"
  - secure: "GF+J61wc3x6W2WKvLWNbeElP4GzFBNQlLwjlBLpwob0Qtwu2KZL+Gj57H7o2h3LkEISuFGdZtcHmSs6k3hEC/DcnY7/K011eSe862FskwgWPkLw9r8TvAgIHm27c1OBLKRPTfNARt5aN3HVWiqPogZcfL5YZmxoWlZmnxevbQ2L1yh11+gsi5Gbw5owr3TiHwnxp8c8ysKfJbLRnpbxdNwwLAUp/U41zu6vVQutHNTo92tbys30F3aZwCJlzze/v9WcJ3DK744Mce5bgkFYhMRXtK2eGG/YBzMD7p3TrCFpkFnFqoVP72pUMPzyfEBsfKsa46VvwokSj7DjdSsdJQOvVLPtjLcxYfSWvc9mrgxSnnTKD+sJe751Zi/PaQzlr86wKH0v79GnoHgMHY3bpzy+nb6TS4yTuG6gyHr7Xnwp+KYPUJMptZ4g0vlIZNeVnF//pIMA+fl9Kc+cKlKYf7TWi36+1uieY6D4VYnJToqoCeYl97cK4GvmnT8Uvr8DN9TjXPsgZPJmanlRsUoodBffJUxMSnyzlx2L0iuc3BXNG5hDTKS3t9DqiAld6L46bZnpzj7pYdNqpfhTm5lm61EH4ImYxcYbhjkidJi6zIh3GNuA23EsDerGUPoooUdZ1h5RIfSrf69JunMgt25M73mHIIm46vRiDxE54Pv7HEcE="

script: 
  - bash ci.bash

notifications:
  webhooks:
    urls:
    - 'https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
